/**
 * Automated management memo — "What management should know this month"
 */

import type { HealthScoreResult, SurvivalEstimate, RatioResult } from '../types';
import type { FinancialAlert } from '../alerts';

export interface ManagementMemoInput {
  companyName: string;
  periodLabel: string;
  health: HealthScoreResult;
  survival: SurvivalEstimate;
  ratios: RatioResult[];
  alerts: FinancialAlert[];
  topFindings: string[];
  topActions: string[];
}

export function buildManagementMemo(input: ManagementMemoInput): string {
  const { companyName, periodLabel, health, survival, alerts, topFindings, topActions } = input;
  const lines: string[] = [
    `MANAGEMENT MEMO — ${companyName}`,
    `Period: ${periodLabel}`,
    `Generated: ${new Date().toISOString().slice(0, 10)}`,
    '',
    '1. FINANCIAL POSITION',
    `   Health score: ${health.overallScore}/100 (${health.classification.replace(/_/g, ' ')})`,
    `   12-month survival estimate: ${survival.survivalProbability12m}% (confidence ${survival.confidence}%)`,
    `   Base-case runway: ${survival.runwayMonthsBase ?? 'N/A'} months`,
    `   Failure risk: ${survival.failureRisk}`,
    `   Primary constraint: ${survival.primaryConstraint}`,
    '',
    '2. MAJOR CHANGES / WATCHPOINTS',
  ];

  if (alerts.length === 0) {
    lines.push('   No threshold alerts triggered in this analysis.');
  } else {
    for (const a of alerts.slice(0, 8)) {
      lines.push(`   [${a.severity}] ${a.message}`);
    }
  }

  lines.push('', '3. KEY RISKS');
  if (topFindings.length === 0) lines.push('   None elevated.');
  else topFindings.slice(0, 5).forEach((f, i) => lines.push(`   ${i + 1}. ${f}`));

  lines.push('', '4. DECISIONS REQUIRED');
  if (survival.failureRisk === 'CRITICAL' || survival.failureRisk === 'SEVERE') {
    lines.push('   Board-level review of liquidity and going-concern options is recommended.');
  } else if (health.overallScore < 60) {
    lines.push('   Management should approve a 30–90 day stabilization plan.');
  } else {
    lines.push('   Continue scheduled monitoring; no emergency decision required from this run alone.');
  }

  lines.push('', '5. RECOMMENDED ACTIONS');
  if (topActions.length === 0) lines.push('   Maintain current controls and reporting cadence.');
  else topActions.slice(0, 5).forEach((a, i) => lines.push(`   ${i + 1}. ${a}`));

  lines.push(
    '',
    '6. METRICS TO MONITOR',
    '   - Cash balance and 13-week cash forecast',
    '   - Operating cash flow trajectory',
    '   - Current ratio and working capital',
    '   - Interest coverage / covenant headroom',
    '   - Health score and runway estimate on each new period upload',
    '',
    'This memo is generated by an AI-assisted analytical system. It does not replace professional advice.',
    'Survival estimates are probabilistic and assumption-dependent.'
  );

  return lines.join('\n');
}
